name = "gestion"
main = "worker.js"
compatibility_date = "2026-01-01"

[durable_objects]
bindings = [
  { name = "CONTADOR_DO", class_name = "GestorVisitasDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GestorVisitasDO"]